version: "3.3"

services:
  filebrowser:
    container_name: "filebrowser"
    build: .
    volumes:
      - "/filebrowser/datafiles:/datafiles"

networks: 
  default:
    external:
      name: filebrowser
